proxy:
  secretToken: SECRET

auth:
  type: github
  github:
    clientId: "2cb5e09d5733ff2e6ae3"
    clientSecret: SECRET
    callbackUrl: "http://pangeo.pydata.org/hub/oauth_callback"
  admin:
    access: true
    users:
      - mrocklin
      - jhamman
      - rabernat
      - yuvipanda
      - choldgraf
